app_host: "0.0.0.0"
app_port: 80

pg:
  host: "db"
  port: 5432
  user: "test"
  password: "123"
  database: "test_tasks"

logging:
  root_log_level: 10
  modules:
    - name: pika
      log_level: 30

filer:
  url: "http://files:80"
  connect_timeout: 3
  read_timeout: 15
  auto_comment: "Изображение было автоматически обработано"
  server_save_path: ""

rabbit:
  host: rabbit
  port: 5672
  user: test
  password: test
  routing_key: tasks
  queue_name: tasks

work_dir: "/uploads"