version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test_files
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - ./development/storage:/var/lib/postgresql/data
      - ./development/init:/docker-entrypoint-initdb.d
    networks:
      - app

  files:
    image: cracher/filer:latest
    restart: always
    volumes:
      - /home/nikita/PycharmProjects/File-service-flask/config.yaml:/config.yaml
    networks:
      - app
    command: uwsgi --ini ../uwsgi.ini

  tasks:
    build: .
    restart: always
    volumes:
      - ./config.yaml:/config.yaml
    networks:
      - app
    command: uwsgi --ini ../uwsgi.ini

  rabbit:
    image: rabbitmq:4.1.1-management
    hostname: rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - /var/lib/rabbitmq
    networks:
      - app

  worker:
    deploy:
      replicas: 3
    build: .
    restart: always
    command: [ "python3", "-u", "scripts/tasks_worker.py" ]
    volumes:
      - ./config.yaml:/config.yaml
    networks:
      - app

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app

networks:
  app: