version: "3.9"

services:
  db_files:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test_files
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - files_db_data:/var/lib/postgresql/data
    networks:
      - app
    ports:
      - "5432:5432"

  db_tasks:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test_tasks
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - tasker_db_data:/var/lib/postgresql/data
    networks:
      - app
    ports:
      - "5433:5432"

  filer:
    image: cracher/filer:latest
    restart: always
    depends_on:
      - db_files
    volumes:
      - /home/nikita/PycharmProjects/File-service-flask/config.yaml:/config.yaml
    networks:
      - app
    ports:
      - "80:80"
    command: uwsgi --ini ../uwsgi.ini

  tasker:
    build: .
    restart: always
    depends_on:
      - filer
      - db_tasks
      - rabbit
    volumes:
      - ./config.yaml:/config.yaml
    networks:
      - app
    ports:
      - "81:80"
    command: uwsgi --ini ../uwsgi.ini

  rabbit:
    image: rabbitmq:4.1.1-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

  worker: &workers
    build: .
    restart: always
    command: [ "python3", "-u", "scripts/tasks_worker.py" ]
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - tasker
    networks:
      - app

  worker1:
    <<: *workers

  worker2:
    <<: *workers

  worker3:
    <<: *workers


volumes:
  files_db_data:
  tasker_db_data:
  rabbitmq_data:
networks:
  app: